#!/usr/bin/env python

#a Documentation
# Imported from the php version
#
# Xilinx bugs...
#   map must be run with -ignore_keep_hierarchy on 7.1 else it core dumps
#   xst adds 'keep_hierarchy' to _all_ submodules of a model when it synthesizes it if the xcf file has 'model $model keep_hierarchy=yes'
# File format
# Each line is of the format:
# c_model <dir> <src> [c_options]
# c_src <dir> <src> [c_options]
#   source is in <source root>/<dir>/<src>.cpp
#   if a c_model, then it is added to the list of models for initialization at library startup, else its just source code
# ef <dir> <model> - 
# clib <libray>
#   specifies a required C library for simulation
# cdl <dir> <model> <cdl_options>
#
# c_options are one or more of:
#  inc:<path> - add include path, relative to the source root
#  def:<thing> - use for -D<thing>
# cdl_options are one or more of:
#  model:<name> - change the output model name to be <name>, and its C code goes to <name>.cpp, object to <name>.o
#  rmn:<mapping> - add --remap-module-name <mapping> to the CDL run, so that the module name and CPP class names may be remapped
#  rmr:<mapping> - add --remap-registered-name <mapping> to the CDL run, so that a module registered name (as can be used in SIM) may be remapped
#  rim:<mapping> - add --remap-implementation-name <mapping> to the CDL run, so that a module may declare a particular implementation name
#  rit:<mapping> - add --remap-instance-type <foo.bar=banana> to the CDL run, so that submodules may be remapped
#  inc:<path> - add include path, relative to the source root
#  dc:<constant setting> - define a constant override for the CDL run (adds --constant <constant setting> to the CDL command line)
#
# XILINX STUFF TBA
#
# Simulation makefile output
#
# The following variables are created:
# MODEL_LIBS - set of libraries required by the models, ready for 'link', i.e. -l<lib> *
# MODELS - list of models that are required for the simulation (from CDL, C and EF)
# C_MODEL_SRCS - list of the source files for the C models (from C only) that are required for the simulation - must be .cpp files
# C_MODEL_OBJS - list of the object files for the models for simulation (from CDL, C and EF) - in target_dir
# VERILOG_FILES - list of the verilog files created by the CDL models, in target_dir
#
# The following rules are created
#  For each C model, <obj> from <src>
#   c++ -o <obj> <src> <options>
#  For each CDL model, <obj> from <src>
#   cdl --model <model> --cpp <cobj> <options> <src>
#   c++ -o <obj> <cobj>
#  For each CDL model, <verilog> from <src>
#   cdl --model <model> --verilog <v> <options> <src>
#
# The simulation Makefile (simulation_build_make) builds a simulation engine with all the models in it
#  It uses ${MODELS} for initialization
#  It links all C_MODEL_OBJS with MODEL_LIBS and the simulation engine for the simulation executable
#  It links all C_MODEL_OBJS with MODEL_LIBS and the simulation engine for the python library

#a Copyright
#  
#  This file 'create_make' copyright Gavin J Stark 2006, 2011
#  
#  This is free software; you can redistribute it and/or modify it however you wish,
#  with no obligations
#  
#  This software is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even implied warranty of MERCHANTABILITY
#  or FITNESS FOR A PARTICULAR PURPOSE.

#a Imports
import sys
import getopt
import os
import re

#a Static global variables - models, libs, base_options
#v parse_models - c_model, c_src, ef, cdl, lib
models = { "c":[],
           "ef":[],
           "cdl":[],
           "cdl_no_cpp":[],
           "hash":{},
           }
libs = { "c":[],
         }
base_options = []
           
#a Read the descriptor list
#f read_objs
def read_objs( model_list_file ):
    object_list = []
    for buffer in model_list_file:
        if (re.match("^\s*#", buffer)):
            continue
        if (re.match("^\s*;", buffer)):
            continue
        result = re.match("^\s*(\S+)\s+(\S.*)", buffer)
        if result:
            object = {}
            object["type"] = result.group(1)
            object["args"] = result.group(2).split()
            object_list.append( object )
    return object_list

#f objs_of_type
def objs_of_type( object_list, type_list ):
    selection = []
    for object in object_list:
        if object["type"] in type_list:
            selection.append( object )
    return selection

#f parse_c_model
def parse_c_model( model_object ):
    model_type = model_object["type"]
    (dir, model_name) = model_object["args"][0:2]

    args = []
    if len(model_object["args"])>2:
        args = model_object["args"]

    options = []
    for option in args[2:]:
        (o,v) = parse_arg(option)
        if o=="inc":
            options.append("-I${SRC_ROOT}/"+v)
        if o=="def":
            options.append("-D"+v)

    object = { "type":model_type,
               "dir":dir,
               "model":model_name,
               "opts":options
               }
    models["c"].append(object)
    models["hash"][model_name] = "c"

#f parse_arg
def parse_arg( arg ):
    result = re.match("([^:]+):(\S+)", arg)
    if result!=None:
        return result.group(1), result.group(2)
    return ("","")

#f parse_ef
def parse_ef( model_object ):
    object = {}
    model_type = model_object["type"]
    dir        = model_object["args"][0]
    model_name = model_object["args"][1]
    object["type"] = model_type
    object["dir"] = dir
    object["model"] = model_name
    object["src"]   = model_name+".ef"
    object["c"]     = model_name+".cpp"
    object["obj"]   = model_name+".o"

    args = []
    if len(model_object["args"])>2:
        args = model_object["args"]

    options = list(base_options) # Copy base_options - it is local to this object now
    for option in args[2:]:
        (o,v) = parse_arg(option)
        if o=="model":
            model_name = v
            object["model"] = model_name
            object["c"]     = model_name+".cpp"
            object["obj"]   = model_name+".o"
        if o=="rmn":
            options.append("--remap-module-name")
            options.append(v)
        if o=="rit":
            options.append("--remap-instance-type")
            options.append(v)
        if o=="rim":
            options.append("--remap-implementation-name")
            options.append(v)
        if o=="rmr":
            options.append("--remap-registered-name")
            options.append(v)

    object["opts"] = options
    models["ef"].append(object)
    models["hash"][model_name] = "ef"

#f parse_clib
def parse_clib( model_object ):
    object = { "lib":model_object["args"][0],
               }
    libs["c"].append( object )

#f parse_cdl_option
def parse_cdl_option( selection, cdl_options ):
    for option in selection["args"]:
        (o,v) = parse_arg(option)
        for (opt_short, opt_name) in [("ass",  "assertions"),
                                      ("sv",   "system_verilog"),
                                      ("disp", "displays"),
                                      ("mul",  "multithread"),
                                      ("cov",  "coverage"),
                                      ("stmt", "statements") ]:
            if o==opt_short:
                cdl_options[opt_name] = "off"
                if v=="on":
                    cdl_options[opt_name] = "on"

#f sanitize_flags
def sanitize_flags( flags ):
    if ',' in flags:
        flags = re.sub(',', '${COMMA}', flags)
    if '(' in flags:
        flags = re.sub('\(', '\(', flags)
    if ')' in flags:
        flags = re.sub('\)', '\)', flags)
    return flags

#f parse_cdl
def parse_cdl( model_object, cdl_options ):
    object = {}
    model_type = model_object["type"]
    dir        = model_object["args"][0]
    model_name = model_object["args"][1]
    object["type"] = model_type
    object["dir"] = dir
    object["model"] = model_name
    object["src"]   = model_name+".cdl"
    object["v"]     = model_name+".v"

    if model_type != "cdl_no_cpp":
        object["c"]     = model_name+".cpp"
        object["obj"]   = model_name+".o"

    args = []
    if len(model_object["args"])>2:
        args = model_object["args"]

    base_options = []
    if (cdl_options["extra_cdlflags"]!=None): base_options.append(sanitize_flags(cdl_options["extra_cdlflags"]))
    if (cdl_options["assertions"]=="on"):  base_options.extend(["--include-assertions"])
    if (cdl_options["system_verilog"]=="on"):  base_options.extend(["--sv-assertions"])
    if (cdl_options["displays"]=="on"):  base_options.extend(["--v_displays"])
    if (cdl_options["coverage"]=="on"):    base_options.extend(["--include-coverage"])
    if (cdl_options["statements"]=="on"):  base_options.append("--include-stmt-coverage")
    if (cdl_options["multithread"]=="on"): base_options.append("--multithread")

    options = list(base_options)
    for option in args[2:]:
        (o,v) = parse_arg(option)
        if o=="model":
            model_name = v
            object["model"] = model_name
            object["v"]     = model_name+".v"

            if model_type != "cdl_no_cpp":
                object["c"]     = model_name+".cpp"
                object["obj"]   = model_name+".o"
                pass
            pass
        if o=="rmn":
            options.append("--remap-module-name")
            options.append(v)
        if o=="rim":
            options.append("--remap-implementation-name")
            options.append(v)
        if o=="rmr":
            options.append("--remap-registered-name")
            options.append(v)
        if o=="rit":
            options.append("--remap-instance-type")
            options.append(v)
        if o=="rmt":
            options.append("--type-remap")
            options.append(v)
        if o=="inc":
            options.append("--include-dir")
            options.append("${SRC_ROOT}/"+v)
        if o=="dc":
            options.append("--constant")
            options.append(v)
        if o=="vapi":
            options.append("--v_additional_port_include")
            options.append(v)
        if o=="vabi":
            options.append("--v_additional_body_include")
            options.append(v)

    options.append("--coverage-desc-file")
    options.append("${TARGET_DIR}/"+model_name+".map")

    object["opts"] = options
    if model_type != "cdl_no_cpp":
        models["cdl"].append(object)
    else:
        models["cdl_no_cpp"].append(object)
    models["hash"][model_name] = object

#f parse_models
def parse_models( object_list, extra_cdlflags ):
    for selection in objs_of_type(object_list,["c_model", "c_src"]):
        parse_c_model( selection )

    for selection in objs_of_type(object_list,["ef"]):
        parse_ef_model( selection )

    for selection in objs_of_type(object_list,["clib"]):
        parse_clib( selection )

    cdl_options = { "coverage":"off",
                    "system_verilog":"off",
                    "assertions":"off",
                    "multithread":"off",
                    "statements":"off",
                    "displays":"off",
                    "extra_cdlflags":extra_cdlflags }
    for selection in objs_of_type(object_list,["cdl", "cdl_options", "cdl_no_cpp"]):
        if selection["type"]=="cdl_options":
            parse_cdl_option( selection, cdl_options )
        else:
            parse_cdl( selection, cdl_options )

#f ZZZ parse_xilinx_descs
def parse_xilinx_descs( object_list ):
    pass
#    $xilinx["srcs"] = array();
#    $xilinx["macros"] = array();
#    $xilinx["rpms"] = array();
#    $xilinx["rams"] = array();
#    $xilinx["cores"] = array();
#    $xilinx["subs"] = array();
#    $xilinx["comps"] = array();
#    $xilinx["toplevel"] = array();
#    $xilinx["type"] = array();
#
#    # A Xilinx source file is expected to define a model of the same name, and it should be a .v file in the 'src' directory of the emulation tree
#    # Xilinx source files should only be referenced by Xilinx subcomponents and components
#    # A Xilinx source file with the same name as another model takes preference over that other model in Xilinx components
#    foreach (objs_of_type($objs,"/^xilinx_src/") as $sel)
#    {
#        $src = $sel["args"][0];
#        $obj = array();
#        $obj["model"] = $src;
#        $xilinx["srcs"][$src] = $obj;
#        $xilinx["type"][$src] = "src";
#    }
#
#    # A Xilinx macro is expected to define a model of the same name, and it should be a .v file in the 'macro' directory of the emulation tree
#    # Xilinx macro should only be referenced by Xilinx subcomponents and components
#    # A Xilinx macro with the same name as another model takes preference over that other model in Xilinx components
#    foreach (objs_of_type($objs,"/^xilinx_macro/") as $sel)
#    {
#        $src = $sel["args"][0];
#        $obj = array();
#        $obj["model"] = $src;
#        $xilinx["macros"][$src] = $obj;
#        $xilinx["type"][$src] = "macro";
#    }
#
#    # A RAM is a Xilinx-specific item that is used in cores; it does not define a model
#    foreach (objs_of_type($objs,"/^xilinx_ram/") as $sel)
#    {
#        $src = $sel["args"][0];
#        $xilinx["rams"][] = $src;
#        $xilinx["type"][$src] = "ram";
#    }
#
#    # A core has a '.xco' file in 'cores', and may depend on RAMs or perhaps other things
#    # It defines a Xilinx-specific model.
#    # If a core is specified with the same name as another model, the core takes preference over that other model in Xilinx components
#    # A core will generate its own '.ngc' file
#    # The core should also generate a behavioural verilog file
#    foreach (objs_of_type($objs,"/^xilinx_core/") as $sel)
#    {
#        $src = $sel["args"][0];
#        $obj = array();
#        $obj["model"] = $src;
#        $obj["src"] = $src;
#        $obj["subs"] = array_slice($sel["args"],1);
#        $xilinx["cores"][$src] = $obj;
#        $xilinx["type"]["$src"] = "core";
#    }
#    # subcomponents are groups of source files, subcomponents, cores, components, or models
#    # a subcomponent is expected to have a model or source file that defines it, that is also declared
#    # subcomponents are basically handy groupings
#    foreach (objs_of_type($objs,"/^xilinx_subcomponent/") as $sel)
#    {
#        $src = $sel["args"][0];
#        $obj = array();
#        $obj["model"] = $src;
#        $obj["subs"] = array_slice($sel["args"],1);
#        $obj["src_models"] = array(); # The source models that make up the component
#        $obj["srcs"] = array(); # The sources (models/components/cores) (and their types) that make up the component
#        $xilinx["subs"][$src] = $obj;
#        $xilinx["type"][$src] = "sub";
#    }
#    # components are items that are built in the Xilinx world, and they consist of models, Xilinx source, and cores
#    # They may utilize subcomponents as a convenience, but subcomponents are not separately built (just used to gather files together neatly)
#    # A component will generate its own '.ngc' file
#    foreach (objs_of_type($objs,"/^xilinx_component/") as $sel)
#    {
#        $src = $sel["args"][0];
#        $obj = array();
#        $obj["model"] = $src;
#        $obj["subs"] = array_slice($sel["args"],1);
#        $obj["src_models"] = array(); # The source models that make up the component
#        $obj["srcs"] = array(); # The sources (models/components/cores) (and their types) that make up the component
#        $xilinx["comps"][$src] = $obj;
#        $xilinx["type"][$src] = "comp";
#    }
#    # A Xilinx RPM converts a component into a relationally-placed macro; it needs a floorplanner file as well as the component
#    # It requires some offline work to create a .ngc file from the floorplanner file and the synthesized ngc file.
#    foreach (objs_of_type($objs,"/^xilinx_rpm/") as $sel)
#    {
#        $src = $sel["args"][0];
#        $obj = array();
#        $obj["model"] = $src;
#        $xilinx["rpms"][$src] = $obj;
#        $xilinx["type"][$src] = "rpm";
#    }
#    # toplevels are built (if components...) with IOBs
#    foreach (objs_of_type($objs,"/^xilinx_toplevel/") as $sel)
#    {
#        echo "Parsing toplevel '".$sel["args"][0]."'\n";
#        $src = $sel["args"][0];
#        $obj["model"] = $sel["args"][1];
#        $obj["device"] = $sel["args"][2];
#        $obj["constraints"] = $sel["args"][3];
#        $xilinx["toplevels"][$src] = $obj;

#f ZZZ find_xilinx_source
# Find the source of a model
# Look first in $xilinx["type"][$model]
def find_xilinx_source( model ):
    pass
#    global $models, $xilinx;
#    $type = NULL;
#    $xtype = NULL;
#    if (isset($models["hash"][$model]))
#    {
#        $type = $models["hash"][$model];
#    }
#    if (isset($xilinx["type"][$model]))
#    {
#        $xtype = $xilinx["type"][$model];
#    }
#    if ($xtype)
#    {
#        return array("xmodel", $xtype );
#    }
#    if ($type)
#    {
#        return array("model", $type );
#    }
#    return NULL;

#a ZZZ Build hierarchy
#f build_xilinx_hierarchy
# We here build the hierarchy for a Xilinx build
# In the Xilinx world we build components, which are made up of other components, cores, or source files
# The hierarchy is dug back as far as a component, no further.
# We use subcomponents to group source files or other components together; they are for convenience, and do not effect build hierarchy
# So for each component we need to identify all its constituents, and where they are subcomponents we must dig back deeper.
# The first thing to do, therefore, is hack down the subcomponents
def build_xilinx_hierarchy():
    pass
#    global $models, $xilinx;
#
#    #b Build subcomponents down to their base constituents
#    $iter = 0;
#    # We need to iterate whilst changes occur...
#    $done = 0;
#    while (!$done)
#    {
#        #b Stop us going round forever!
#        $iter++;
#        if ($iter>50)
#        {
#            echo "Too many iterations in subcomponent hierarchy examination - probably a loop in the Xilinx components; check '$last_model'\n";
#            exit(4);
#        }
#        #b Run through all xilinx_subcomponents
#        $done = 1;
#        foreach ($xilinx["subs"] as $key=>$obj)
#        {
#            #b the subcomponent must be a xilinx source or model
#            # we expect to find its source and type in the source list
#            $src_models = $obj["src_models"];
#            $srcs = $obj["srcs"];
#            $model = $obj["model"];
#            #echo "Model $model now has source ";print_r($src_models);echo"\n";
#            #b Ensure the source for the subcomponent is in its own list
#            if (!in_array($model, $src_models))
#            {
#                $type = find_xilinx_source( $model );
#                if (!$type)
#                {
#                    echo "Subcomponent $model has no associated source file\n";
#                    exit(4);
#                }
#                #echo "Adding self $model\n";
#                $src_models[] = $model;
#                $srcs[] = array( $type, $model );
#                $done = 0;
#                $last_model = $model;
#            }
#            #b Run through all of the subcomponent ($obj)'s subs 
#            foreach ($obj["subs"] as $model)
#            {
#                #b Find the type of the subcomponent's sub ($model)
#                $type = find_xilinx_source( $model );
#                #echo "Sub $model type ";print_r($type);
#                if (!$type)
#                {
#                    echo "Subcomponent constituent $model has no associated source file\n";
#                    exit(4);
#                }
#                #b Add its source to the list for the subcomponent if not already present
#                if (!array_search($model, $src_models))
#                {
#                    $src_models[] = $model;
#                    $srcs[] = array( $type, $model );
#                    $last_model = $model;
#                    $done = 0;
#                }
#                #b If $model is a xilinx_subcomponent, then add all its source models to the set (if not already there)!
#                if ( ($type[0]=="xmodel") &&
#                     ($type[1]=="sub") )
#                {
#                    foreach ($xilinx["subs"][$model]["src_models"] as $src_model)
#                    {
#                        if (!in_array($src_model, $src_models))
#                        {
#                            $subtype = find_xilinx_source( $src_model );
#                            $src_models[] = $src_model;
#                            $srcs[] = array( $subtype, $src_model );
#                            $last_model = $model;
#                            $done = 0;
#                        }
#                    }
#                }
#            }
#            #b Set the sources for the subcomponent $obj
#            $xilinx["subs"][$key]["src_models"] = $src_models;
#            $xilinx["subs"][$key]["srcs"] = $srcs;
#            #print_r($src_models);
#        }
#    }
#
#    #b Now build components down to their base constituents
#    foreach ($xilinx["comps"] as $key=>$obj)
#    {
#        #b Clear arrys of sources and source models
#        $src_models = array();
#        $srcs = array();
#        #b the component must be a xilinx source or model
#        $model = $obj["model"];
#        $type = find_xilinx_source( $model );
#        if (!$type)
#        {
#            echo "Component $model has no associated source file\n";
#            exit(4);
#        }
#        #b Okay, so we have a source model - it may be a xilinx_src, xilinx_macro, or CDL source
#        $src_models[] = $model;
#        $srcs[] = array( $type, $model );
#        #b Now run through all the subcomponents
#        foreach ($obj["subs"] as $model)
#        {
#            #b Find type of subcomponent of our component
#            $type = find_xilinx_source( $model );
#            if (!$type)
#            {
#                echo "Component constituent $model has no associated source file\n";
#                exit(4);
#            }
#            #b Add it to the source models and sources, if it is not already there
#            if (!array_search($model, $src_models))
#            {
#                $src_models[] = $model;
#                $srcs[] = array( $type, $model );
#            }
#            #b If it is a xilinx_subcomponent, then push down in to that to add its sources also
#            if ( ($type[0]=="xmodel") &&
#                 ($type[1]=="sub") )
#            {
#                #b Add each source of our component's subs
#                foreach ($xilinx["subs"][$model]["src_models"] as $submodel)
#                {
#                    if (!in_array($submodel, $src_models))
#                    {
#                        $subtype = find_xilinx_source( $submodel );
#                        $src_models[] = $submodel;
#                        $srcs[] = array( $subtype, $submodel );
#                    }
#                }
#            }
#            #b Done that subcomponent
#        }
#        #b Set the sources and source models for the component to be the lists generated
#        $xilinx["comps"][$key]["src_models"] = $src_models;
#        $xilinx["comps"][$key]["srcs"] = $srcs;
#        #b Done that component

#a Model makefile
#f options_string_from_list
def options_string_from_list( option_list ):
    options = ""
    for opt in option_list:
        options = options + " " + opt
    return options

#f output_model_makefile
def output_model_makefile( output_file ):

    print >>output_file, "include ${CDL_SCRIPTS_DIR}/cdl_templates.mk"
    print >>output_file
    print >>output_file, "#a Variables"
    print >>output_file, "COMMA := ,"
    print >>output_file, "MODEL_LIBS := \\"
    for lib in libs["c"]:
        print >>output_file, "    -l"+lib["lib"]+" \\"
    print >>output_file

    print >>output_file, "MODELS :="
    print >>output_file, "C_MODEL_SRCS :="
    print >>output_file, "C_MODEL_OBJS :="
    print >>output_file, "VERILOG_FILES := "
    print >>output_file, "CDLH_FILES = "

    print >>output_file
    print >>output_file, "#a C models"
    for model in models["c"]:
        c_filename      = model["dir"]+"/"+model["model"]+".cpp"
        object_filename = model["model"]+".o"
        options = options_string_from_list(model["opts"])
        if (model["type"] == "c_model"):
            model_name = model["model"]
            print >>output_file, """$(eval $(call cmodel_template,%s,%s,%s,%s))""" % (c_filename, object_filename, model_name, options)
        else:
            print >>output_file, """$(eval $(call csrc_template,%s,%s,%s))""" % (c_filename, object_filename, options)
    
    print >>output_file
    print >>output_file, "#a EF models"
    for model in models["ef"]:
        directory = model["dir"]
        model_name = model["model"]
        source_file = model["src"]
        c_filename = model["c"]
        object_filename = model["obj"]
        ef_filename = directory + "/" + source_file
        options = options_string_from_list(model["opts"])
        print >>output_file, """$(eval $(call ef_template,%s,%s,%s,%s,%s))""" % (ef_filename, c_filename, model_name, object_filename, options)

    print >>output_file
    print >>output_file, "#a CDL models"
    for model in models["cdl"]:
        directory = model["dir"]
        model_name = model["model"]
        source_file = model["src"]
        c_filename = model["c"]
        object_filename = model["obj"]
        verilog_filename = model["v"]
        cdl_filename = directory + "/" + source_file
        options = options_string_from_list(model["opts"])
        print >>output_file, """$(eval $(call cdl_template,%s,%s,%s,%s,%s,%s))""" % (cdl_filename, c_filename, model_name, object_filename, verilog_filename, options)

    print >>output_file
    print >>output_file, "#a CDL models with no CPP"
    if models.has_key("cdl_no_cpp"):
        for model in models["cdl_no_cpp"]:
            directory = model["dir"]
            model_name = model["model"]
            source_file = model["src"]
            c_filename = "None"
            object_filename = "None"
            verilog_filename = model["v"]
            cdl_filename = directory + "/" + source_file
            options = options_string_from_list(model["opts"])
            print >>output_file, """$(eval $(call cdl_no_cpp_template,%s,%s,%s,%s,%s,%s))""" % (cdl_filename, c_filename, model_name, object_filename, verilog_filename, options)

    print >>output_file, "cdlh: ${CDLH_FILES}"
    print >>output_file, "xml: ${XML_FILES}"

#a Handle options
#f usage
def usage(rc):
    print >>sys.stderr, """\
create_make -f <model_list> [-x <xilinx makefile>] [-m simulation/emulation makefile] [other options]
    Other options
    -toplevel toplevel for xilinx build (required for xilinx makefiles if rpm not given)
    -rpm rpm for xilinx buid (required for xilinx makefiles if toplevel not given)

The program creates makefiles for building simulations and emulations
"""
    exit(rc)

#b read in options
# args is the list of options that need an argument - the text here is the default values
args={"model_list":"please specify which file to use as the model_list",
      "sim_makefile":None,
      "xilinx_makefile":None,
      "extra_cdlflags":None,
    }
arg_options = ["model_list", "sim_makefile", "xilinx_makefile", "extra_cdlflags"] # List of all options
arg_shoptions = {"f":"model_list", "m":"sim_makefile", "x":"xilinx_makefile" }

getopt_options = []
for x in arg_options:
    if x not in args.keys():
        args[x] = None
    getopt_options.append( x+"=" )

getopt_shopts = ""
for x in arg_shoptions.keys():
    getopt_shopts = getopt_shopts + x + ":"

try:
    (optlist,file_list) = getopt.getopt(sys.argv[1:],getopt_shopts,getopt_options)
except:
    print >>sys.stderr, "Exception parsing options:", sys.exc_info()[1]
    usage(4)

for opt,value in optlist:
    if opt[1:] in arg_shoptions.keys():
        opt = "--"+arg_shoptions[opt[1:]]
    if (opt[0:2]=='--') and (opt[2:] in arg_options):
        args[opt[2:]] = value
    else:
        print >>sys.stderr, "Unknown option", opt, "with value", value
        usage(4)

model_list_filename = args["model_list"]
simulation_make_filename =  args["sim_makefile"]
xilinx_make_filename =  args["xilinx_makefile"]
extra_cdlflags = args["extra_cdlflags"]

#a Main
model_list = open( model_list_filename )
if not model_list:
    print >>sys.stderr, "Failed to open file model list file", model_list_filename
    usage(4)

object_list = read_objs( model_list )
model_list.close()

parse_models( object_list, extra_cdlflags )
#parse_xilinx_descs( $objs )
#
#build_xilinx_hierarchy();
#
if simulation_make_filename!=None:
    output_file = open( simulation_make_filename, "w" )
    output_model_makefile( output_file )
    output_file.close()

#if args["xilinx"]!=None:
#    if (!isset($options["t"]) && !!isset($options["r"])):
#        usage(4)
#    toplevel = $options["t"];
#    if (!$xilinx["toplevels"][$toplevel]):
#        echo "xilinx_toplevel '$toplevel' not found in model list when building Xilinx makefile\n";
#        exit(4);
#
#    $file = fopen( $options["x"], 'w' );
#    output_xilinx_makefile( $file, $toplevel );
#    fclose($file);

#a Editor preferences and notes
# Local Variables: ***
# mode: python ***
# outline-regexp: "#[a!]\\\|#[\t ]*[b-z][\t ]" ***
# End: ***

