#a Copyright
#  
#  This file 'Makefile' copyright Gavin J Stark 2003, 2004
#  
#  This is free software; you can redistribute it and/or modify it however you wish,
#  with no obligations
#  
#  This software is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even implied warranty of MERCHANTABILITY
#  or FITNESS FOR A PARTICULAR PURPOSE.

#a Global variables
include ${CDL_ROOT}/Makefile_build_config
include ${CDL_SCRIPTS_DIR}/makefile_hdr

$(eval $(call install_script,create_make))
$(eval $(call install_script,simulation_build_make))
